canonical/starbase

- pyproject.toml
- tox.ini
> lint: stricter ruff rules

- .github/workflows/tests.yaml
- tox.ini
-----
Fixes #81
Upcoming: tox-gh modification to have the GitHub summary be the tox summary
> ci: configure tox to disable listing dependencies

- .github/workflows/tests.yaml
> ci: cache pip packages

- HACKING.rst
- pyproject.toml
- tox.ini
> tox: improve UX

- .github/workflows/tests.yaml
- tests/integration/test_setuptools.py
> ci: separate unit and integration tests

- .github/workflows/release-publish.yaml
> ci: make release publisher workflow fetch correct tags

- .github/renovate.json5
I'm not 100% sure this works, but I may have been really, really dumb in my inability to figure this out
-----
> renovate: fix scheduling

- .github/workflows/tests.yaml
-----
Upstream from https://github.com/canonical/craft-providers/pull/400
> ci(renovate): run tests on renovate branches

- .github/renovate.json5
- .github/workflows/check-renovate.yaml
> chore: update renovate config

- .github/renovate.json5
- .github/workflows/check-renovate.yaml
> build: run Renovate immediately on craft-* patch releases

- pyproject.toml
> style(lint): bump max function args to 8

- pyproject.toml
> style(lint): private member access

- pyproject.toml
> style(lint): disable magic value check in tests

- pyproject.toml
- tests/conftest.py
- tests/integration/test_setuptools.py
- tests/integration/test_version.py
- tests/unit/starbase/test_init.py
- tox.ini
-----
Please raise any opinions here. If we don't have unanimity on rules we shouldn't include them.
> style: stricter ruff linters

- .github/renovate.json5
> chore: make renovate update pre-commit-config

- pyproject.toml
> style: ignore docstring requirements for overrides

- .github/workflows/docs.yaml
- .github/workflows/release-publish.yaml
- .github/workflows/tests.yaml
> ci(deps): update artifact actions

- .github/renovate.json5
> ci(deps): make renovate update pyright separately.

- .github/renovate.json5
> ci: fix regex for pre-commit-config.yaml

- pyproject.toml
- tox.ini
> chore: update ruff settings

- .github/workflows/tests.yaml
- pyproject.toml
- starcraft/__init__.py
- tox.ini
-----
macos 14 (arm64) runners don't have Python 3.8 available: https://github.com/canonical/starbase/actions/runs/8822488158/job/24221000391?pr=205
> build: update minimum Python version to 3.10

- .github/workflows/tests.yaml
- HACKING.rst
- pyproject.toml
- tox.ini
-----
macos test error is fixed in #208
> chore: switch to codespell snap

- docs/conf.py
- pyproject.toml
> docs: use canonical-sphinx

- pyproject.toml
- starcraft/__init__.py
- tests/integration/starbase/test_init.py
- tests/integration/test_setuptools.py
- tests/integration/test_version.py
- tests/unit/starbase/test_init.py
- tox.ini
> style: replace black formatter with ruff format

- .github/workflows/tests.yaml
https://github.com/actions/runner-images/issues/9848
-----
> ci: run tests on Ubuntu 24.04

- .github/renovate.json5
- .github/workflows/check-renovate.yaml
> ci: remove deprecated renovate config options

- .editorconfig
- tox.ini
> chore: update line length configuration

- HACKING.rst
-----
Refining changelog convention now that they are getting used in more projects.
source: https://github.com/canonical/craft-application/pull/377
> docs(HACKING): add details on changelog convention

- HACKING.rst
-----
Add explanation for when to use an exclamation point in a commit message header.
> docs: update hacking with explanation for exclamation point

- tests/conftest.py
> style: autoformat with ruff 0.6

- tests/conftest.py
> style(lint): autoformat

- .gitignore
- Makefile
- pyproject.toml
> build(tools): add a Makefile that uses uv

- HACKING.rst
-----
Minor change for merges.  I think the quotes are superfluous.
> docs: update commit headers for merges

- .github/workflows/release-publish.yaml
> chore(ci): generate release notes when publishing

- docs/release-notes/index.rst
> docs: add app cadence, update deprecation notice in release notes index

- docs/release-notes/index.rst
> docs: remove release policy from rn index

- .pre-commit-config.yaml
- pyproject.toml
---
@bepri pointed these out in https://github.com/canonical/charmcraft/pull/2074
> style: update linting configuration for ruff 0.9

- pyproject.toml
We install it separately (either from snap from uv) anyway.
---
> build(deps): remove pyright

- docs/release-notes/index.rst
- For notes, add text describing how present tense with "now" is permissible, and add examples that demonstrate it.
- Make it clearer that the items in the fixed issue list should be links.
---
> docs: make minor improvements to release note template

- common.mk
> fix(common.mk): fix glob of prettier files

- README.rst
---
Gets some more spacing errors that I somehow missed in #331. Oops.
> docs: fix some formatting errors in README

- Makefile
> fix(make): generate a list of build dependencies and run one command

- common.mk
> fix(make): depend on build deps during setup

- HACKING.rst
---
Adds a note about how to describe reverts in a conventional-commit fashion.
> docs(HACKING): add note about revert commits

- docs/conf.py
- docs/redirects.txt
- pyproject.toml
- uv.lock
> feat(docs): add redirects

- HACKING.rst
> style(HACKING): fix typo

- README.rst
> docs: clarify the steps for merging starbase into a project

- pyproject.toml
---
Upstream of https://github.com/canonical/craft-parts/pull/1045.
> style: enforce strict checking for shadowing

- .github/workflows/release-publish.yaml
---
Inspired by and supersedes https://github.com/canonical/starbase/pull/371
> ci: fixups for the publish workflow

- docs/release-notes/index.rst
> docs: add patch fixes to release notes template

- .github/workflows/tics.yaml
- Makefile
- common.mk
- pyproject.toml
- uv.lock
> feat: environment for TICS

- common.mk
- pyproject.toml
> Charmcraft imported improvements

- docs/conf.py
- pyproject.toml
- uv.lock
---
* Adds a Matrix link and the "Give feedback" button to the `conf.py` template.
* Changes docs dependency to `canonical-sphinx[full]`
[RTD build](https://canonical-starbase--403.com.readthedocs.build/en/403/)
> docs: add links and buttons to conf.py

- Makefile
- common.mk
> style: add pre-commit to auto-formatting

- .pre-commit-config.yaml
- tests/conftest.py
> style: fix linting for ruff 0.12

- pyproject.toml
> style: add TC001, TC002 and TC003 rules

- common.mk
---
Updates `make setup` to run all `setup-*` targets. This ensures that all system packages are installed on running `make setup`.
> fix: install system packages during setup

- .github/workflows/release-publish.yaml
On our self-hosted runners we need to specify --yes
---
> ci: fix publish workflow

- .gitignore
> fix(gitignore): only ignore a top-level parts dir
