- pyproject.toml
-----
`SIM117` is a good rule in theory.  In practice, it seems to make the code less readable (especially with 88 character line lengths).
> lint: ignore ruff SIM117

- pyproject.toml
- tests/integration/starbase/test_version.py
-----
The versioning is now a close match to [snapcraft's versioning scheme](https://github.com/snapcore/snapcraft/blob/6b94548db638ddb17acf49b7340a2b801a1ab4e7/tools/version.py#L25-L30) using [setuptools-scm](https://github.com/pypa/setuptools_scm/tree/main).  Getting it any closer will require creating a custom [Version](https://github.com/pypa/packaging/blob/63f4cfe679fb3d9322e56d8569207ecff4735238/src/packaging/version.py#L157) class.
(CRAFT-1794)
> meta: use snapcraft's versioning scheme

- pyproject.toml
- tests/integration/test_version.py
-----
Adds a dirty flag to the version when the working dir is dirty.
This functionality was already part of `setuptool_scm`.  I had previously removed it to keep aligned with [snapcraft's scheme](https://github.com/snapcore/snapcraft/blob/40136ea9b59351e4f9f1fbed8c4d8c0db873c488/tools/version.py#L24).  After an offline discussion, I think it's better to align with `setuptools_scm`.
Also moves the integration test up a directory.
> meta: add dirty flag to versioning scheme

- pyproject.toml
- tests/integration/starbase/test_setuptools.py
The directive is finnicky with regards to globbing, so the tests and docs were being included in the final wheel package.
-----
> tools: fix 'setuptools.package.find' directive

- tests/conftest.py
- tests/integration/test_setuptools.py
- tests/integration/test_version.py
The idea is this: since we have a few tests that are worth running in "downstream" projects (those that merge starbase periodically), instead of having to adapt every test individually in every downstream project we'll use a fixture (project_main_module) that provides the imported module object. So in starbase is returns the 'starcraft' module.
The tests are then updated to use this fixture instead of importing the module directly. Downstream projects therefore only need to update the fixture's implementation and the tests will (well, should) work.
-----
Feel free to shoot this PR down, we can reject this with no problems. It's just an idea that occurred to me because the versioning and packaging tests are actually very useful in downstream projects too.
> tests: provide a fixture with the project's 'main' module

- pyproject.toml
-----
This will automatically exclude type-checking guard blocks from coverage, as they are never run.
> coverage: automatically exclude type checking blocks

- pyproject.toml
-----
After internal discussion it was decided that mandating type-checking guard blocks is not preferred.
> ruff: remove type-checking guard blocks

- .github/renovate.json5
-----
`branchConcurrentLimit` was implicitly set to `prConcurrentLimit`, which can prevent automerges and PR from being created.
source: https://github.com/canonical/craft-providers/pull/395
https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit
> ci(renovate): allow more branches

- pyproject.toml
see: https://docs.astral.sh/ruff/settings/#pep8-naming-classmethod-decorators
-----
> style: ensure ruff picks up pydantic.validator for class methods

- .github/workflows/docs.yaml
- .github/workflows/tests.yaml
-----
Colorize the output of tox in Github CI.
Tox does not colorize its output in Github because of the envvar `TERM` is set to `dumb`. However, github handles colorized output quite nicely.
Upstream of https://github.com/snapcore/snapcraft/pull/4435 / https://github.com/canonical/craft-providers/pull/442
> ci: colorize tox

- .github/renovate.json5
Now that ruff has had a 0.1 release it should be updatable with our other linters.
-----
> chore(deps): include ruff in dev updates

- .github/renovate.json5
- .github/workflows/tests.yaml
- HACKING.rst
-----
Updates to commit message guidelines to be more descriptive and authoritative.
Preview RST [here](https://github.com/canonical/starbase/blob/conventional-commit-documentation/HACKING.rst)
> docs(HACKING): update commit message guidelines

- .github/renovate.json5
- pyproject.toml
- tests/unit/starbase/test_init.py
* Disable pyright complaints for mocks
* Move `types/pyright` into renovate's pyright group
-----
> build(deps): update pyright

- .pre-commit-config.yaml
> chore: make pre-commit linters use lint group for renovate

- pyproject.toml
The modified dependencies are known to be sufficiently stable that the given version ranges are unlikely to cause breakages.
-----
> build: loosen requirements

- .github/workflows/release-publish.yaml
This commit updates the Release workflow with the following changes:
- Use self-hosted jammy machines instead of default Github runners;
- Use PyPI's Trusted Publishers to publish, replacing the PYPI_API_TOKEN;
- (minor) Constrain the artifacts that are attached to the Github release.
-----
> ci: update Release workflow

- .github/renovate.json5
- .github/workflows/check-renovate.yaml
>  ci: update renovate config and workflow

- .github/renovate.json5
Renovate should only PR to hotfix branches for non-dev patch updates.
-----
Lint issue is unrelated.
> chore(renovate): fewer PRs to hotfix branches

- .readthedocs.yaml
- README.rst
- docs/index.rst
- Clarify the wording in the README, add more details about preparing the docs.
- Disable PDF and EPUB generation. We can re-enable this later when we rebase the docs and those builds are working again.
-----
> docs: update readme and template, fix build error

- README.rst
> docs(readme): add badges

- docs/index.rst
- pyproject.toml
Port in fixes:
https://github.com/canonical/craft-application/commit/8b2b8f36cab1f42d2b6f8d46d109edbd18fba08d#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534R18
Because I want CI passing on my "upstreaming" PR.
-----
> feat: port sphinx fix

- Makefile
-----
Somehow a few little issues slipped through the healthy reviewage in https://github.com/canonical/starbase/pull/265
> fix: starbase breakage from #265

- .readthedocs.yaml
RTD updated their CI on Tuesday 19th November 2024, switching default version of python `3` from `3.12` to `3.13`.
As `starbase` does not support this version yet, we'll pin the version to the latest supported one.
Closes: #283 
(CRAFT-3710)
> ci(rtd): pin python version to 3.12

- docs/explanation/index.rst
- docs/how-to-guides/index.rst
- docs/index.rst
- docs/reference/index.rst
- docs/release-notes/index.rst
- docs/tutorials/index.rst
Release notes occupy their own top-level section in the documentation TOC.
The template for individual release notes is included as a comment at the end of the index. This follows a pattern set by our changelogs. If there's a better way of including copyable templates, please chime in!
-----
CRAFT-3712
> docs: add release notes index and template

- Makefile
- common.mk
> fix: fix issues found in common.mk with charmcraft

- common.mk
This adds ::group:: tags around linters if the CI environment variable is set, which allows the linters to be collapsed in CI.
-----
> feat(common.mk): group linters in CI

- README.rst
- common.mk
-----
Several small issues found when recently using starbase to init a project.
> fix: Typos in doc and make files 

- pyproject.toml
-----
The 'slow' mark is used in `test_setuptools.py` and should be present by default if we want to push the adoption of the slow/fast tests dichotomy.
> feat: register the 'slow' mark to pytest

- .github/renovate.json5
We've moved to using a default config location for renovate in starflow.
-----
> fix: update renovate config

- common.mk
- pyproject.toml
This changes the way we get pyright, preferring the snap and no longer having it frozen to a specific version.
As requested by @sergiusens : https://github.com/canonical/craft-store/pull/241#discussion_r1883817892
-----
> feat: use existing, then snap, then uv pyright

- .github/workflows/release-publish.yaml
The `gh-action-pypi-publish` pulls in a docker image to do the actual publishing, and said image is apparently always amd64
-----
> ci: restrict pypi job to amd64

- common.mk
Issue found here: https://github.com/canonical/craft-store/pull/241#pullrequestreview-2502863941
-----
> fix: use uv tool run for pre-commit if not global

- common.mk
> fix(common.mk): freeze UV by default.

- common.mk
See: https://github.com/canonical/charmcraft/pull/2096
---
> fix(common.mk): docs ignores

- README.rst
---
The README was missing some newlines that caused `#.`s to remain in their `#` form instead of turning into a new ordered sub-list.
> docs: fix spacing errors in README

- .github/PULL_REQUEST_TEMPLATE.md
- .readthedocs.yaml
- common.mk
- pyproject.toml
- uv.lock
This switches from using extras to using dependency groups, now that they are [considered standard](https://packaging.python.org/en/latest/specifications/dependency-groups/#dependency-groups).
It also adjusts the readthedocs build to use uv so that we can use those groups, with a side effect of speeding up the RTD builds (more noticeable here than in bigger projects).
As a drive-by, it also fixes the PR template.
This is marked as a breaking change because the changes to pyproject.toml and common.mk are mutually dependent.
> build!: switch from using extras to dependency groups

- common.mk
Resolve erroneous link warnings affecting literalref directives. Sphinx-lint will no longer check for spaces before angle brackets (\`\` <>\`\`) or underscores after graves (\`\`_).
The root cause is a bug in our implementation of literalref: https://github.com/canonical/canonical-sphinx-extensions/issues/47
---
> fix(common.mk): skip frivolous link checks in lint-docs

- .readthedocs.yaml
This is sometimes needs in cases where readthedocs' default clone doesn't include the tags.
---
> ci: fetch tags on readthedocs

- common.mk
---
A couple of the linter tasks were so noisy that previous linting steps would be completely flooded off of the terminal. This PR just quiets it down a bit.
> chore: hush some of the linter output

- README.rst
- SECURITY.md
---
Language was reviewed by the Security Engineering team once already. All content is my own addition except for the text under "Reporting a vulnerability".
CRAFT-3700.
> docs: add SECURITY.md template

- common.mk
---
A new makefile target to more easily identify tests that should be marked with `@pytest.mark.slow` will help with starbase adoption.
> feat: new makefile target to identify slow tests

- pyproject.toml
---
ANN10* ruff rules have been deprecated and removed since they were so commonly ignored. This PR removes it to fix TOML validators complaining.
> chore: remove now-deprecated linter rule

- .readthedocs.yaml
In keeping with recent changes to Rockcraft and Snapcraft.
---
---
> docs(rtd): switch to extensionless URLS

- .gitignore
---
Ignore the `.idea/` directory from PyCharm and other IDEs from JetBrains.
Upstreamed from [snapcraft](https://github.com/canonical/snapcraft/blob/5e21a93fc2ab8bea9e49b0cf941c10adff0f5bf1/.gitignore#L112).
> feat: ignore jetbrain config directory

- pyproject.toml
---
Fixes a couple of pieces of the pyproject that got out of date
- specifying the license in the classifiers field is deprecated, and should instead be an SPDX specifier in the `project.license` field
- adjusted the dynamic README field to reference a markdown instead of a rST file after #365
- cleaning up some whitespace
> build: fix a couple pieces of base pyproject

- Makefile
---
The `publish` target in the makefile was superseded by PyPI's CI integration, now used in starflow.
> chore: remove obsolete publish target

- .readthedocs.yaml
---
This addresses a reoccurring and silent problem in Snapcraft where doc warnings would not show up in CI ([source](https://github.com/canonical/snapcraft/pull/5468), [source](https://github.com/canonical/snapcraft/pull/5436)).
> docs: fail on RTD warnings

- common.mk
---
As seen in https://github.com/canonical/craft-cli/pull/340#discussion_r2075409736, jinja templates need to be ignored by shellcheck
> style: ignore jinja templates

- common.mk
Using `--all-files` for pre-commit format affects more files than `make format` would otherwise do.
---
> fix: walk back pre-commit all-files

- docs/conf.py
---
We get a lot of linkcheck errors in CI. I don't want to disable it as it's very useful, so I want to see if we can make it more forgiving instead.
I've also proposed what I think is a better (more resilient) solution upstream, since that solution will handle it when sites give 500-series errors for a long time.: https://github.com/sphinx-doc/sphinx/issues/13898
> docs: make linkcheck more forgiving
